name: Quadeca Website Tracker

on:
  schedule:
    # Run every 30 minutes
    - cron: '*/30 * * * *'
  workflow_dispatch:  # Allows manual triggering

jobs:
  check-for-updates:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 twilio
          
      - name: Run update checker
        env:
          TWILIO_ACCOUNT_SID: ${{ secrets.TWILIO_ACCOUNT_SID }}
          TWILIO_AUTH_TOKEN: ${{ secrets.TWILIO_AUTH_TOKEN }}
          TWILIO_FROM_NUMBER: ${{ secrets.TWILIO_FROM_NUMBER }}
          YOUR_PHONE_NUMBER: ${{ secrets.YOUR_PHONE_NUMBER }}
        run: python QUADTRACKER.py
        
      - name: Commit any changes to state file
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add last_known_state.json
          git diff --quiet && git diff --staged --quiet || git commit -m "Update last known state [skip ci]"
          git push
